
trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Job1
  steps:
  - script: echo job1
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    displayName: 'Run a multi-line script'
- job: Job2
  steps:
    - script: echo job2
      displayName: 'one-line-script'
    - script: |
        echo multiline script
      displayName: 'multi-line-script'
- job: Job3
  dependsOn: 
   - Job1
   - Job2
  steps: 
    - script: echo job3
- job: Job4
  dependsOn: 
    Job2
  steps: 
    - script: echo job4
